using System;
using System.Collections.Generic;
using System.Text;

namespace TextAdventure.Core
{
    public enum NamedGlyph : int
    {
        // 1 @ 0-15
        BLANK = 0,
        SMILEY = 1,
        SMILEY_INVERT = 2,
        HEART = 3,
        LOZANGE = 4,
        TREFFLE = 5,
        SPADE = 6,
        SMALLDOT = 7,
        SMALLDOT_INVERT = 8,
        BIGDOT = 9,
        BIGDOT_INVERT = 10,
        MALE = 11,
        FEMALE = 12,
        SINGLE_NOTE = 13, QUAVER = SINGLE_NOTE,
        DOUBLE_NOTE = 14, BEAMED_NOTES = DOUBLE_NOTE,
        SNOWFLAKE = 15,

        // 2 @ 16-31
        CARRET_RIGHT = 16,
        CARRET_LEFT = 17,
        VERTICAL_SCROLL = 18,
        TWO_EXCLAMATION_MARKS = 19, DOUBLE_EXCLAMATION_MARKS = 19,
        PARAGRAPH = 20,
        SIMOLEON = 21,
        QUARTER_HEIGHT_BLOCK = 22,
        VERTICAL_SCROLL_END = 23,
        ARROW_UP = 24,
        ARROW_DOWN = 25,
        ARROW_RIGHT = 26,
        ARROW_LEFT = 27,
        DIVISION_CORNER = 28,
        HORIZONTAL_SCOLL = 29,
        CARRET_UP = 30,
        CARRET_DOWN = 31,

        // 3 @ 32-47
        BLANK_2 = 32,
        EXCLAMATION_MARK = 33, EXCLAMATION_POINT = EXCLAMATION_MARK,
        QUOTE = 34,
        POUND = 35,
        DOLLAR = 36,
        PERCENT = 37,
        AMPERSAND = 38,
        APOSTROPHE = 39, SINGLE_QUOTE = APOSTROPHE,
        PARENTHESIS_OPEN = 40,
        PARENTHESIS_CLOSE = 41,
        ASTERISK = 42,
        PLUS = 43,
        COMMA = 44,
        MINUS = 45,
        PERIOD = 46,
        FORWARD_SLASH = 47,

        // 4 @ 48-63
        ZERO = 48,
        ONE = 49,
        TWO = 50,
        THREE = 51,
        FOUR = 52,
        FIVE = 53,
        SIX = 54,
        SEVEN = 55,
        EIGHT = 56,
        NINE = 57,
        COLON = 58,
        SEMI_COLON = 59,
        LESS_THAN = 60,
        EQUAL = 61,
        GREATER_THAN = 62,
        QUESTION_MARK = 63,

        // 5 @ 64-79
        AT = 64,
        A = 65,
        B = 66,
        C = 67,
        D = 68,
        E = 69,
        F = 70,
        G = 71,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,

        // 6 @ 80-95
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        BRACKET_OPEN, // [
        BACK_SLASH, // /
        BRACKET_CLOSE, // ]
        CARAT,
        UNDERSCORE, // _

        // 7 @ 96-111
        BACK_QUOTE,
        a,
        b,
        c,
        d,
        e,
        f,
        g,
        h,
        i,
        j,
        k,
        l,
        m,
        n,
        o,

        // 8 @ 112-127
        p,
        q,
        r,
        s,
        t,
        u,
        v,
        w,
        x,
        y,
        z,
        BRACES_OPEN,
        PIPE, BAR = PIPE,
        BRACES_CLOSE,
        TILDE,
        HOUSE,

        // 9 @ 128-143
        Ç,
        ü,
        é,
        â,
        ä,
        à,
        a_WITH_CIRCLE_ON_TOP,
        ç,
        ê,
        ë,
        è,
        ï,
        î,
        ì,
        Ä,
        A_WITH_CIRCLE_ON_TOP,

        // 10 @ 144-159,
        É,
        UNKNOWN_0,
        WEIRD_A,
        ô,
        ö,
        ò,
        û,
        ÿ,
        Ö,
        Ü,
        CENT,
        BRITISH_POUND,
        YEN,
        PT,
        FUNCTION,

        // 11 @ 160-175
        á,
        í,
        ó,
        ú,
        n_WITH_TILDE,
        N_WITH_TILDE,
        A_UNDERSCORE,
        O_UNDERSCORE,
        UPSIDE_DOWN_QUESTION_MARK,
        GUN_RIGHT,
        GUN_LEFT,
        HALF,
        QUARTER,
        UPSIDE_DOWN_EXCLAMATION_MARK,
        FRENCH_QUOTES_OPEN,
        FRENCH_QUOTES_CLOSE,

        // 12 @ 176-191
        FADE_LOW = 176,
        FADE_MEDIUM = 177,
        FADE_HIGH = 178,
        PIPE_VERTICAL = 179,
        PIPE_VERTICAL_SIDEPIPE = 180,
        PIPE_VERTICAL_DOUBLE_SIDEPIPE = 181,
        PLACEHOLDER_182 = 182,
        PLACEHOLDER_183 = 183,
        PLACEHOLDER_184 = 184,
        PLACEHOLDER_185 = 185,
        PLACEHOLDER_186 = 186,
        PLACEHOLDER_187 = 187,
        PLACEHOLDER_188 = 188,
        PLACEHOLDER_189 = 189,
        PLACEHOLDER_190 = 190,
        PLACEHOLDER_191 = 191,

        // 13 @ 192-207

    }
}
